### ISSUE TITLE
回环检测Intensity scan context 的intensity calibration

### ISSUE THREAD

**Issue by lyk125** [JokerJohn/xchu_slam#2]
你好：
       请问，你在使用Intensity scan context时，怎么做的intensity calibration呢？原论文介绍的这块没怎么看明白

**Comment by JokerJohn** [comment]
Intensity calibration需要参考2014年斯坦福的一篇文章，在本文中是直接略过的，稍后我补充道知乎这篇博客里面。





------------------ 原始邮件 ------------------
发件人: lyk125 ***@***.***&gt;
发送时间: 2021年6月24日 17:05
收件人: JokerJohn/xchu_slam ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[JokerJohn/xchu_slam] 回环检测Intensity scan context 的intensity calibration (#2)





 
你好：
 请问，你在使用Intensity scan context时，怎么做的intensity calibration呢？原论文介绍的这块没怎么看明白

**Comment by lyk125** [comment]
非常感谢！
